name: /home/wade/miniconda3/envs/python39
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgomp=13.2.0=h807b86a_2
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.43.2=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.4=hd590300_0
  - pip=23.3.1=pyhd8ed1ab_0
  - python=3.9.18=h0755675_0_cpython
  - readline=8.2=h8228510_1
  - tk=8.6.13=h2797004_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - arabic-reshaper==3.0.0
      - astunparse==1.6.3
      - beautifulsoup4==4.12.2
      - blosc2==2.2.9
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.1
      - contourpy==1.1.1
      - cryptography==41.0.5
      - cycler==0.12.1
      - dukpy==0.3.0
      - elementpath==4.1.5
      - esprima==4.0.1
      - et-xmlfile==1.1.0
      - ffpyplayer==4.5.1
      - fonttools==4.43.1
      - freetype-py==2.4.0
      - future==0.18.3
      - gevent==23.9.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - greenlet==3.0.1
      - html2text==2020.1.16
      - idna==3.4
      - imageio==2.31.6
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.1.0
      - javascripthon==0.12
      - jedi==0.19.1
      - json-tricks==3.17.3
      - kiwisolver==1.4.5
      - markdown-it-py==3.0.0
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - msgpack==1.0.7
      - msgpack-numpy==0.4.8
      - ndindex==1.7
      - numexpr==2.8.7
      - numpy==1.26.1
      - opencv-python==4.8.1.78
      - openpyxl==3.1.2
      - packaging==23.2
      - pandas==2.1.2
      - parso==0.8.3
      - pillow==10.0.1
      - psutil==5.9.6
      - psychopy==2023.2.3
      - psychopy-sounddevice==0.0.1
      - psychtoolbox==3.0.19.0
      - py-cpuinfo==9.0.0
      - pycparser==2.21
      - pyglet==1.5.27
      - pyparallel==0.2.2
      - pyparsing==3.1.1
      - pypi-search==2.0
      - pypng==0.20220715.0
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyserial==3.5
      - python-bidi==0.4.2
      - python-dateutil==2.8.2
      - python-gitlab==3.15.0
      - python-vlc==3.0.18122
      - python-xlib==0.33
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - questplus==2023.1
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - scipy==1.11.3
      - setuptools==66.1.1
      - six==1.16.0
      - smmap==5.0.1
      - sounddevice==0.4.6
      - soundfile==0.12.1
      - soupsieve==2.5
      - tables==3.9.1
      - tzdata==2023.3
      - ujson==5.8.0
      - urllib3==2.0.7
      - websockets==12.0
      - wxpython==4.2.1
      - xarray==2023.10.1
      - xmlschema==2.5.0
      - zipp==3.17.0
      - zope-event==5.0
      - zope-interface==6.1
prefix: /home/wade/miniconda3/envs/python39
