name: tetris_flow
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.11=hd590300_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - jack=1.9.22=h7c63dc7_2
  - ld_impl_linux-64=2.40=h41732ed_0
  - libdb=6.2.32=h9c3ff4c_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgomp=13.2.0=h807b86a_5
  - libnsl=2.0.1=hd590300_0
  - libopus=1.3.1=h7f98852_1
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4.20240210=h59595ed_0
  - openssl=3.2.1=hd590300_1
  - pip=24.0=pyhd8ed1ab_0
  - portaudio=19.6.0=h7c63dc7_9
  - pyaudio=0.2.14=py38h01eb140_0
  - python=3.8.19=hd12c33a_0_cpython
  - python_abi=3.8=4_cp38
  - readline=8.2=h8228510_1
  - setuptools=69.5.1=pyhd8ed1ab_0
  - sqlite=3.45.2=h2c6b66d_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - pip:
      - arabic-reshaper==2.1.3
      - astunparse==1.6.3
      - attrs==21.4.0
      - automat==20.2.0
      - cachetools==5.0.0
      - certifi==2021.10.8
      - cffi==1.15.0
      - charset-normalizer==2.0.12
      - constantly==15.1.0
      - cryptography==36.0.2
      - cycler==0.11.0
      - decorator==4.4.2
      - distro==1.7.0
      - dukpy==0.2.3
      - esprima==4.0.1
      - et-xmlfile==1.1.0
      - fonttools==4.32.0
      - freetype-py==2.2.0
      - future==0.18.2
      - gevent==21.12.0
      - gitdb==4.0.9
      - gitpython==3.1.27
      - glfw==2.5.3
      - google-api-core==2.7.2
      - google-auth==2.6.5
      - google-cloud==0.34.0
      - google-cloud-speech==2.13.1
      - googleapis-common-protos==1.56.0
      - greenlet==1.1.2
      - grpcio==1.44.0
      - grpcio-status==1.44.0
      - hyperlink==21.0.0
      - idna==3.3
      - imageio==2.17.0
      - imageio-ffmpeg==0.4.7
      - incremental==21.3.0
      - javascripthon==0.11
      - jedi==0.18.1
      - json-tricks==3.15.5
      - kiwisolver==1.4.2
      - macropy3==1.1.0b2
      - markdown-it-py==2.1.0
      - matplotlib==3.5.1
      - mdurl==0.1.1
      - moviepy==1.0.3
      - msgpack==1.0.3
      - msgpack-numpy==0.4.7.1
      - numexpr==2.8.1
      - numpy==1.22.3
      - opencv-python==4.5.5.64
      - openpyxl==3.0.9
      - packaging==21.3
      - pandas==1.4.2
      - parso==0.8.3
      - pillow==9.1.0
      - proglog==0.1.9
      - proto-plus==1.20.3
      - protobuf==3.20.0
      - psutil==5.9.0
      - psychtoolbox==3.0.18.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - pygame==2.1.2
      - pyglet==1.4.11
      - pyo==1.0.4
      - pyparallel==0.2.2
      - pyparsing==3.0.8
      - pypng==0.20220715.0
      - pyqt5==5.15.6
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.10.1
      - pyserial==3.5
      - python-bidi==0.4.2
      - python-dateutil==2.8.2
      - python-gitlab==3.3.0
      - python-vlc==3.0.16120
      - python-xlib==0.31
      - pytz==2022.1
      - pyyaml==6.0
      - pyzmq==22.3.0
      - questplus==2019.4
      - requests==2.27.1
      - requests-toolbelt==0.9.1
      - rsa==4.8
      - scipy==1.8.0
      - six==1.16.0
      - smmap==5.0.0
      - sounddevice==0.4.4
      - soundfile==0.10.3.post1
      - speechrecognition==3.8.1
      - tables==3.7.0
      - tobii-research==1.9.0
      - tqdm==4.64.0
      - twisted==22.4.0
      - typing-extensions==4.2.0
      - ujson==5.2.0
      - urllib3==1.26.9
      - websocket-client==1.3.2
      - xarray==2022.3.0
      - xlrd==2.0.1
      - zope-event==4.5.0
      - zope-interface==5.4.0
prefix: /home/wade/mambaforge/envs/tetris_flow
